export const siteConfig = {
  siteName: "ClintDoesDev",
  developerName: "Clinton",
  jobTitle: "Full-stack Developer · Websites, SaaS & Digital Products",
  defaultTitle: "Web Developer in Nigeria | ClintDoesDev",
  defaultDescription:
    "Clinton is a full-stack developer based in Nigeria who builds landing pages, marketing sites, SaaS platforms, dashboards, and web applications for founders, startups, and businesses.",
  locale: "en_NG",
  language: "en-NG",
  countryName: "Nigeria",
  socialImage: "/assets/profilepic.jpeg",
  keywords: [
    "web developer in Nigeria",
    "Nigeria web developer",
    "full-stack developer Nigeria",
    "frontend developer Nigeria",
    "React developer Nigeria",
    "Next.js developer Nigeria",
    "Node.js developer Nigeria",
    "TypeScript developer Nigeria",
    "website developer Nigeria",
    "landing page developer nigeria",
    "website developer nigeria",
    "business website nigeria",
    "web application developer Nigeria",
    "ecommerce website developer Nigeria",
    "dashboard developer Nigeria",
    "hire web developer in Nigeria",
    "custom software developer Nigeria",
    "portfolio web developer Nigeria",
  ],
  serviceTypes: [
    "Custom website development",
    "Landing Page Development",
    "Marketing & Business Websites",
    "Client Website Builds",
    "Full-stack web application development",
    "Next.js and React development",
    "Node.js API development",
    "Dashboard and admin panel development",
    "E-commerce development",
    "Web3 Platform Development",
    "NFT & Blockchain Integration",
    "SaaS Dashboard Development",
    "Technical SEO implementation",
    "Performance optimization",
  ],
  coreStack: [
    "React",
    "Next.js",
    "TypeScript",
    "Node.js",
    "Web3",
    "Blockchain",
    "Solidity",
    "Ethers.js",
    "Paystack",
    "PostgreSQL",
    "MongoDB",
    "SEO",
    "Core Web Vitals",
  ],
} as const;
