export const siteConfig = {
  siteName: "ClintDoesDev",
  developerName: "Clinton",
  defaultTitle: "Web Developer in Nigeria | ClintDoesDev",
  defaultDescription:
    "Nigeria-based full-stack web developer building fast websites, web apps, dashboards, APIs, and e-commerce platforms with Next.js, React, TypeScript, and Node.js.",
  locale: "en_NG",
  language: "en-NG",
  countryName: "Nigeria",
  socialImage: "/assets/profilepic.jpeg",
  keywords: [
    "web developer in Nigeria",
    "Nigeria web developer",
    "full-stack developer Nigeria",
    "frontend developer Nigeria",
    "React developer Nigeria",
    "Next.js developer Nigeria",
    "Node.js developer Nigeria",
    "TypeScript developer Nigeria",
    "website developer Nigeria",
    "web application developer Nigeria",
    "ecommerce website developer Nigeria",
    "dashboard developer Nigeria",
    "hire web developer in Nigeria",
    "custom software developer Nigeria",
    "portfolio web developer Nigeria",
  ],
  serviceTypes: [
    "Custom website development",
    "Full-stack web application development",
    "Next.js and React development",
    "Node.js API development",
    "Dashboard and admin panel development",
    "E-commerce development",
    "Technical SEO implementation",
    "Performance optimization",
  ],
  coreStack: [
    "React",
    "Next.js",
    "TypeScript",
    "Node.js",
    "PostgreSQL",
    "MongoDB",
    "SEO",
    "Core Web Vitals",
  ],
} as const;
